trigger:
  branches:
    include:
    - main
  paths:
    include:
    - policies/initiatives/**
  batch: true

variables:
  serviceConnectionDev: 'id-policy-vending-eus-dev-001'
  serviceConnectionTest: 'id-policy-vending-eus-test-001'
  serviceConnectionProd: 'id-policy-vending-eus-prod-001'
  subscriptionIdDev: '243c3cf8-1a50-4b3c-a45e-0d1f0a82a37b'
  subscriptionIdTest: 'b7762cc9-e968-4152-9cb5-f283738190f4'
  subscriptionIdProd: 'ef4541ca-58de-411a-bed5-3127d75ee4a2'

pool: 'default'

stages:
- stage: Dev
  displayName: Dev
  jobs:
  - job: DevJob
    displayName: DevJob
    steps: 
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(serviceConnectionDev)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
            az account set --subscription $(subscriptionIdDev)
            cd policies/initiatives/dev-plb-root

            # Get Azure context and set ARM variables for Azure provider authentication
            SUBSCRIPTION_ID=$(az account show --query id -o tsv)
            TENANT_ID=$(az account show --query tenantId -o tsv)
            CLIENT_ID=$(az account show --query user.name -o tsv)

            # Set ARM environment variables for Terraform Azure provider
            export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
            export ARM_TENANT_ID=$TENANT_ID
            export ARM_CLIENT_ID=$CLIENT_ID
            export ARM_USE_OIDC=true

            # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI
            unset AZURE_CONFIG_DIR
            
            echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
            echo "ARM_TENANT_ID: $ARM_TENANT_ID"
            echo "ARM_CLIENT_ID: $CLIENT_ID"
            echo "ARM_USE_OIDC: $ARM_USE_OIDC"

            terraform init
            # terraform force-unlock -force b92aa416-10c4-d4e5-b2ab-c9fc41c1ad87
            terraform plan
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        failOnStandardError: true
        displayName: 'Terraform Plan (Dev)'

- stage: DeployDev
  displayName: DeployDev
  dependsOn: Dev
  jobs:
  - job: DeployDevJob
    displayName: DeployDevJob
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(serviceConnectionDev)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
            az account set --subscription $(subscriptionIdDev)
            cd policies/initiatives/dev-plb-root

            # Get Azure context and set ARM variables for Azure provider authentication
            SUBSCRIPTION_ID=$(az account show --query id -o tsv)
            TENANT_ID=$(az account show --query tenantId -o tsv)
            CLIENT_ID=$(az account show --query user.name -o tsv)

            # Set ARM environment variables for Terraform Azure provider
            export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
            export ARM_TENANT_ID=$TENANT_ID
            export ARM_CLIENT_ID=$CLIENT_ID
            export ARM_USE_OIDC=true

            # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI
            unset AZURE_CONFIG_DIR
            
            echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
            echo "ARM_TENANT_ID: $ARM_TENANT_ID"
            echo "ARM_CLIENT_ID: $CLIENT_ID"
            echo "ARM_USE_OIDC: $ARM_USE_OIDC"

            terraform init
            terraform apply -auto-approve -parallelism=50
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        failOnStandardError: false
        displayName: 'Terraform Apply (Dev)'

# - stage: Test
#   displayName: Test
#   dependsOn: DeployDev
#   jobs:
#   - job: TestJob
#     displayName: TestJob
#     steps:
#     - task: AzureCLI@2
#       inputs:
#         azureSubscription: $(serviceConnectionTest)
#         scriptType: 'bash'
#         scriptLocation: 'inlineScript'
#         inlineScript: |
#             az account set --subscription $(subscriptionIdTest)
#             cd policies/initiatives/test-plb-root
#
#             # Get Azure context and set ARM variables for Azure provider authentication
#             SUBSCRIPTION_ID=$(az account show --query id -o tsv)
#             TENANT_ID=$(az account show --query tenantId -o tsv)
#             CLIENT_ID=$(az account show --query user.name -o tsv)
#
#             # Set ARM environment variables for Terraform Azure provider
#             export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
#             export ARM_TENANT_ID=$TENANT_ID
#             export ARM_CLIENT_ID=$CLIENT_ID
#             export ARM_USE_OIDC=true
#
#             # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI
#             unset AZURE_CONFIG_DIR
#             
#             echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
#             echo "ARM_TENANT_ID: $ARM_TENANT_ID"
#             echo "ARM_CLIENT_ID: $CLIENT_ID"
#             echo "ARM_USE_OIDC: $ARM_USE_OIDC"
#
#             terraform init
#             terraform plan
#         workingDirectory: '$(System.DefaultWorkingDirectory)'
#         failOnStandardError: true
#         displayName: 'Terraform Plan (Test)'
#
# - stage: DeployTest
#   displayName: DeployTest
#   dependsOn: Test
#   jobs:
#   - job: DeployTestJob
#     displayName: DeployTestJob
#     steps:
#     - task: AzureCLI@2
#       inputs:
#         azureSubscription: $(serviceConnectionTest)
#         scriptType: 'bash'
#         scriptLocation: 'inlineScript'
#         inlineScript: |
#             az account set --subscription $(subscriptionIdTest)
#             cd policies/initiatives/test-plb-root
#
#             # Get Azure context and set ARM variables for Azure provider authentication
#             SUBSCRIPTION_ID=$(az account show --query id -o tsv)
#             TENANT_ID=$(az account show --query tenantId -o tsv)
#             CLIENT_ID=$(az account show --query user.name -o tsv)
#
#             # Set ARM environment variables for Terraform Azure provider
#             export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
#             export ARM_TENANT_ID=$TENANT_ID
#             export ARM_CLIENT_ID=$CLIENT_ID
#             export ARM_USE_OIDC=true
#
#             # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI
#             unset AZURE_CONFIG_DIR
#             
#             echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
#             echo "ARM_TENANT_ID: $ARM_TENANT_ID"
#             echo "ARM_CLIENT_ID: $CLIENT_ID"
#             echo "ARM_USE_OIDC: $ARM_USE_OIDC"
#
#             terraform init
#             terraform apply -auto-approve -parallelism=50
#         workingDirectory: '$(System.DefaultWorkingDirectory)'
#         failOnStandardError: false
#         displayName: 'Terraform Apply (Test)'
#
# - stage: Prod
#   displayName: Prod
#   dependsOn: DeployTest
#   jobs:
#   - job: ProdJob
#     displayName: ProdJob
#     steps:
#     - task: AzureCLI@2
#       inputs:
#         azureSubscription: $(serviceConnectionProd)
#         scriptType: 'bash'
#         scriptLocation: 'inlineScript'
#         inlineScript: |
#             az account set --subscription $(subscriptionIdProd)
#             cd policies/initiatives/plb-root
#
#             # Get Azure context and set ARM variables for Azure provider authentication
#             SUBSCRIPTION_ID=$(az account show --query id -o tsv)
#             TENANT_ID=$(az account show --query tenantId -o tsv)
#             CLIENT_ID=$(az account show --query user.name -o tsv)
#
#             # Set ARM environment variables for Terraform Azure provider
#             export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
#             export ARM_TENANT_ID=$TENANT_ID
#             export ARM_CLIENT_ID=$CLIENT_ID
#             export ARM_USE_OIDC=true
#
#             # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI
#             unset AZURE_CONFIG_DIR
#             
#             echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
#             echo "ARM_TENANT_ID: $ARM_TENANT_ID"
#             echo "ARM_CLIENT_ID: $CLIENT_ID"
#             echo "ARM_USE_OIDC: $ARM_USE_OIDC"
#
#             terraform init
#             terraform plan
#         workingDirectory: '$(System.DefaultWorkingDirectory)'
#         failOnStandardError: true
#         displayName: 'Terraform Plan (Prod)'
#
# - stage: DeployProd
#   displayName: DeployProd
#   dependsOn: Prod
#   jobs:
#   - job: DeployProdJob
#     displayName: DeployProdJob
#     steps:
#     - task: AzureCLI@2
#       inputs:
#         azureSubscription: $(serviceConnectionProd)
#         scriptType: 'bash'
#         scriptLocation: 'inlineScript'
#         inlineScript: |
#             az account set --subscription $(subscriptionIdProd)
#             cd policies/initiatives/plb-root
#
#             # Get Azure context and set ARM variables for Azure provider authentication
#             SUBSCRIPTION_ID=$(az account show --query id -o tsv)
#             TENANT_ID=$(az account show --query tenantId -o tsv)
#             CLIENT_ID=$(az account show --query user.name -o tsv)
#
#             # Set ARM environment variables for Terraform Azure provider
#             export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
#             export ARM_TENANT_ID=$TENANT_ID
#             export ARM_CLIENT_ID=$CLIENT_ID
#             export ARM_USE_OIDC=true
#
#             # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI
#             unset AZURE_CONFIG_DIR
#             
#             echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
#             echo "ARM_TENANT_ID: $ARM_TENANT_ID"
#             echo "ARM_CLIENT_ID: $CLIENT_ID"
#             echo "ARM_USE_OIDC: $ARM_USE_OIDC"
#
#             terraform init
#             terraform apply -auto-approve -parallelism=50
#         workingDirectory: '$(System.DefaultWorkingDirectory)'
#         failOnStandardError: true
#         displayName: 'Terraform apply (Prod)'
